image: python:3-alpine

stages:
  - publish

publish:
  stage: publish
  only:
    refs:
      - master
  script:
    - pip install awscli
    - aws --region us-east-2 s3 sync . s3://srlingren.com-20180520011541205400000001
    - aws cloudfront create-invalidation --distribution-id E26KI76826AIUA --paths "/*"
