image: registry.gitlab.com/lingrino/docker/ci:latest

stages:
  - publish

publish:
  stage: publish
  only:
    refs:
      - master
  script:
    - aws --region "${S3_REGION}" s3 sync . "s3://${S3_BUCKET_NAME}" --sse AES256
    - aws cloudfront create-invalidation --distribution-id "${CF_DISTRIBUTION_ID}" --paths "/*"
